name: Scrape latest data

on:
  schedule:
    - cron:  '3,13,23,33,43,53 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl --user-agent "Mozilla 4.0/" "https://www.uniqlo.com/in/api/commerce/v3/en/products?path=9672&flagCodes=discount&sort=2&limit=1000&offset=0" | jq . > uniq-women.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
